<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>dialplan.rb</string>
	</array>
	<key>keyEquivalent</key>
	<string>^~@r</string>
	<key>name</key>
	<string>Ruby (Adhearsion)</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(menu)\b</string>
			<key>name</key>
			<string>keyword</string>
		</dict>
		<dict>
			<key>include</key>
			<string>source.ruby</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.ruby.adhearsion</string>
	<key>uuid</key>
	<string>2071DC52-5598-4F1A-8223-9EDF15FCA7E6</string>
</dict>
</plist>
